version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_fastapi
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: todo
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"

volumes:
  mongo:
